min_acl: public
clean: true
output: docs
author: 'Daisuke T'
github_url: https://github.com/daisuke-t-jp/BeaconDetectManager
module: BeaconDetectManager
source_directory: BeaconDetectManager
readme: README.md
