language: objective-c
osx_image: xcode10

env:
  global:

before_install:

script:
  - swift --version
  - xcodebuild test -project "BeaconDetectManager/BeaconDetectManager.xcodeproj" -scheme "BeaconDetectManagerTests" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" -configuration Debug

branches:
  only: 
      - master
